/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'smokey' at '6/8/16 10:15 AM' with Gradle 2.13
 *
 * @author smokey, @date 6/8/16 10:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
